name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t odagora/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true odagora/react-test npm test

      - name: Set Identity Provider
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "projects/767179756194/locations/global/workloadIdentityPools/github/providers/my-repo"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: multi-k8s-481117

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: multi-k8s
          location: us-central1
          project_id: multi-k8s-481117

      - name: Build
        run: |-
          docker build -t odagora/multi-client-k8s-gh:latest -t odagora/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t odagora/multi-server-k8s-gh:latest -t odagora/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t odagora/multi-worker-k8s-gh:latest -t odagora/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push odagora/multi-client-k8s-gh:latest
          docker push odagora/multi-server-k8s-gh:latest
          docker push odagora/multi-worker-k8s-gh:latest

          docker push odagora/multi-client-k8s-gh:${{ env.SHA }}
          docker push odagora/multi-server-k8s-gh:${{ env.SHA }}
          docker push odagora/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=odagora/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=odagora/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=odagora/multi-worker-k8s-gh:${{ env.SHA }}
